services:
  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: