name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build containers
        run: |
          APP_ENV_FILE=.env.test docker compose --env-file .env.test up -d --build mongo redis api

      - name: Run tests
        run: |
          APP_ENV_FILE=.env.test docker compose --env-file .env.test exec -T api pytest

      - name: Stop containers
        run: |
          APP_ENV_FILE=.env.test docker compose --env-file .env.test exec -T api pytest
